#!/bin/bash
ORIG_MSG_FILE="$1"
TEMP=`mktemp /tmp/git-XXXXX`

TICKETNO=`git branch | grep '^\*' | cut -b3- | cut -d/ -f2 | cut -d- -f1,2`
TITLE=`git log -1 --pretty=%B | head -1`

if [[ "$TITLE" =~ ^$TICKETNO.* ]]; then
    MSG="$TITLE\n"
else
   MSG="$TICKETNO : \n" 
fi

(echo "$MSG"; cat "$ORIG_MSG_FILE") > "$TEMP"
cat "$TEMP" > "$ORIG_MSG_FILE"
